services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: elixirapi_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
